#!/usr/bin/expect --
spawn /bin/sh WWWDIR/bin/init-db.sh

expect {Would you like to create one now? (yes/no):}
send "yes\r"

expect {Username (leave blank to use 'root'):}
send "DJANGO_USER\r"

expect {E-mail address:}
send "DJANGO_EMAIL\r"

expect {Password:}
send "DJANGO_PASSWORD\r"

expect {Password (again):}
send "DJANGO_PASSWORD\r"

set timeout -1

expect {fixture(s)}
send "\r"

puts "Ended expect script."

